version: "3.8"

services:

  tester:
    image: thenetyeti/envtest:${RELEASE_TAG:-latest}
    build: ./src
    environment:
      - FOO="compose file"
      - BAR="docker-compose.yml with $$FOO from '${FOO}'"
      - FILE="checkit.log"
      - OS_PWD="${PWD}"
      - OS_HOSTNAME=${HOSTNAME:-'hostname'}
    volumes:
      - /:/host
    command: ["/app/checkit", "${FILE}"]
